// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4IRikcw-mJnILyqMe8lER15OvDgMJI8M',
    appId: '1:576897641702:web:5a7d0e067b47c566dddf27',
    messagingSenderId: '576897641702',
    projectId: 'rangeofficerhelper',
    authDomain: 'rangeofficerhelper.firebaseapp.com',
    storageBucket: 'rangeofficerhelper.appspot.com',
    measurementId: 'G-92EK743MT3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbUB7qBAycaWdauYMpWmiu6nLMcP-vcHg',
    appId: '1:576897641702:android:d98e6f3771a2a99bdddf27',
    messagingSenderId: '576897641702',
    projectId: 'rangeofficerhelper',
    storageBucket: 'rangeofficerhelper.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5iMSA8ZiDkQqtPn5tFcdMc9jL1uQHhHA',
    appId: '1:576897641702:ios:1db43dbaa4d47985dddf27',
    messagingSenderId: '576897641702',
    projectId: 'rangeofficerhelper',
    storageBucket: 'rangeofficerhelper.appspot.com',
    iosClientId: '576897641702-k88vbmpg9qvbm19uor9nisfmst8nt2i7.apps.googleusercontent.com',
    iosBundleId: 'com.rangeofficer.rohelper',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5iMSA8ZiDkQqtPn5tFcdMc9jL1uQHhHA',
    appId: '1:576897641702:ios:1db43dbaa4d47985dddf27',
    messagingSenderId: '576897641702',
    projectId: 'rangeofficerhelper',
    storageBucket: 'rangeofficerhelper.appspot.com',
    iosClientId: '576897641702-k88vbmpg9qvbm19uor9nisfmst8nt2i7.apps.googleusercontent.com',
    iosBundleId: 'com.rangeofficer.rohelper',
  );
}
